- library/src/main/kotlin/it/krzeminski/githubactions/domain/RunnerType.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/EndToEndTest.kt
GitHub provides a fairly large set of runners [hosted by them](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners) which are available for users, this PR simply adds all of these runners into the library.
GitHub also provides the ability to have [self-hosted runners](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-self-hosted-runners) which use an array of stringly-typed labels to identify the correct machine to run the job on. This would require a fairly major rework of the API which I can propose in a separate issue if there's interest in supporting the use-case.
> Expand RunnerType to cover all currently available GitHub-hosted runners

- library/src/gen/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8.kt
- wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
The value for "push" can be true/false, but it can also be something like "--force --set-upstream origin dependency-update" which is passed as an argument for git push
> Fix for add-and-commit

- library/src/gen/kotlin/it/krzeminski/githubactions/actions/actions/SetupPythonV2.kt
- wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
- wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
I had a look at my actions from https://github.com/jmfayard/refreshVersions
and this one is the only one I needed that was not present
I also sorted the wrapper requests.
If we don't do that, every one commits to the last element of the list, so we have a merge conflicts each time
> Generate wrapper for actions/setup-python

- wrapper-generator/build.gradle.kts
After recent simplification in the tests, the mocking framework turns out to be
not needed.
> Remove dependency on MockK

- library/src/main/kotlin/it/krzeminski/githubactions/domain/triggers/PullRequest.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/Case.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/yaml/CaseTest.kt
- library/src/test/kotlin/it/krzeminski/githubactions/yaml/TriggersToYamlTest.kt
I am missing `PullRequest.types`
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
Interestingly enough it is identical to  `PullRequestTarget.types` which is already part of the library
I added `Enum.toSnakeCase()` because I think that doing an exhaustive when is more likely to bring us a typo error.
> Add PullRequest.types

- .github/workflows/gradle-wrapper-validation.main.kts
- .github/workflows/gradle-wrapper-validation.yaml
In practice it happens very rarely, so this optimization will reduce
processing power consumption and clutter in PR workflow reports.
> Run Gradle wrapper validation only if wrapper changes

- wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
- wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
When a generated file doesn't match what was expected,
the actual content is written to a file GeneratedFileActual.kt
Use IntelliJ's "Compare Files" Actions
and update GeneratedFile.kt if the change looks good
Next time the test run and match the expected content,
GeneratedFileActual.kt will be deleted
On GitHub Actions, fail instead of creating a new file
> tests: compare GeneratedFile.kt with GeneratedFileActual.kt

- library/src/main/kotlin/it/krzeminski/githubactions/domain/Step.kt
- library/src/main/kotlin/it/krzeminski/githubactions/dsl/JobBuilder.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/StepsToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
- library/src/test/kotlin/it/krzeminski/githubactions/yaml/StepsToYamlTest.kt
To allow writing more compact code. The names are not always needed.
> [#145] feat(library): Make step name optional

- mkdocs.yml
This should add a light/dark mode toggle. It's just a quick suggestion. I haven't tested if it works!
Config copied from: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
> mkdocs.yml - add light/dark mode toggle

- library/src/main/kotlin/it/krzeminski/githubactions/domain/RunnerType.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/yaml/JobsToYamlTest.kt
- script-generator/build.gradle.kts
- script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptgenerator/Jobs.kt
- script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptgenerator/KotlinPoet.kt
- script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptmodel/RunnerTypes.kt
- script-generator/src/test/kotlin/generated/AllTriggers.kt
- script-generator/src/test/kotlin/generated/DockerImage.kt
- script-generator/src/test/kotlin/generated/GenerateWrappers.kt
- script-generator/src/test/kotlin/generated/GeneratedSource.kt
- script-generator/src/test/kotlin/generated/NodeJsPackage.kt
- script-generator/src/test/kotlin/generated/RefreshversionsBuild.kt
- script-generator/src/test/kotlin/generated/RefreshversionsPr.kt
- script-generator/src/test/kotlin/generated/RefreshversionsWebsite.kt
- script-generator/src/test/kotlin/generated/UpdateGradleWrapper.kt
- script-generator/src/test/kotlin/test/EnumsTest.kt
- script-generator/yaml-output/refreshversions-build.yml
Resolves #69 
Changes `RunnerType` from an `Enum` to a `sealed class` with an additional `Custom("my-string")` possible value.
This allows do create a runner type from yet-unsupported value and also do use expressions like in
```kotlin
job(runsOn = RunnerType.Custom(expr("github.event.inputs.run-on")))
```
For the user, this changes how the imports work by default
`runsOn = UbuntuLatest`
to
`runsOn = RunnerType.UbuntuLatest`
> [#69] feat(library): Custom runner type from string

- library/build.gradle.kts
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/DetectMalfomedYaml.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
**What?** 
fail-fast when the YAML is malformed
**Why?**
There are a lots of way to produce invalid YAML with the library.
In this case we should in all cases fail fast instead of letting the user push to GitHub and waste her time.
**How?**
kaml does know whether a given string content is valid YAML or not, so  rely on that.
> fail-fast when the YAML is malformed

- .github/workflows/release.main.kts
- .github/workflows/release.yaml
- library/build.gradle.kts
It's needed to display successful release job status after the library
is really present in Maven Central. Also, after this waiting, some
other things will be released, e.g. the docs.
> [#151] chore(ci): wait until library present in Maven Central after releasing

- docs/supported-actions.md
- library/src/gen/kotlin/it/krzeminski/githubactions/actions/bahmutov/NpmInstallV1.kt
- wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
Using version up to patch number causes a need to update it frequently.
I discovered that this action does expose a major version but through
a branch, not a tag. Only tags are checked by the job that looks for
newer versions. This pontential room for improvement is tracked in #250.
> [#248] feat(wrappers): use v1 for bahmutov/npm-install

- script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptgenerator/GitHubWorkflow.kt
- script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptgenerator/Members.kt
- script-generator/src/test/kotlin/it/krzeminski/githubactions/scriptgenerator/ImportsTest.kt
Hello I noticed a bug in the script-generator while working on my article
There is currently a compile error when you use it because ´expr(String)`  has moved from package `dsl.expr` to `dsl.expressions.expr`
> fix(script-generator): expr(String) is in a new package

- docs/user-guide/script-generator.md
- mkdocs.yml
**What?**
Decouple the latest library version from the recommended script-generator version in the doc at
https://krzema12.github.io/github-actions-kotlin-dsl/user-guide/script-generator/
**Why?**
There may be a breaking change when the library is released.
Coupling both versions
- prevents Piotr from releasing freely
- put some pression on me to adapt the script-generator ASAP
Since the script-generator still works fine in the previously validated version, and updating the library is pretty easy once the script is generated, this coupling is not necessary.
**How?**
New markdown variable
> Decouple the library version and the recommended script-generator version

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/repositories.settings.gradle.kts
- buildSrc/settings.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm.gradle.kts
- library/build.gradle.kts
- script-generator/build.gradle.kts
- settings.gradle.kts
- wrapper-generator/build.gradle.kts
This change incorporates a part of this PR: #194. Introducing in
smaller pieces to reduce blast radius if something goes wrong.
> chore: extract common build logic to a local Gradle plugin

- library/build.gradle.kts
In the previous approach for YAML emitting, it
was used to validate if the YAML is valid. Now
we intend to create the valid YAML right away,
so kaml usage was removed.
> [#80] chore(library): remove unneeded dependency on kaml

- .github/workflows/Integration tests - job condition.yaml
- .github/workflows/Integration tests - multiline command with pipes.yaml
- .github/workflows/Integration tests - one job depending on another.yaml
- .github/workflows/Integration tests - step with outputs.yaml
- .github/workflows/Integration tests - trivial workflow.yaml
- .github/workflows/Integration tests - type-safe expressions.yaml
- library/build.gradle.kts
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/ObjectToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
- library/src/test/kotlin/it/krzeminski/githubactions/yaml/ObjectToYamlTest.kt
The main motivator for this change is being able to not produce anchors
which are not supported by GitHub. Apart from that, this approach gives
us great control over the produced YAML.
> [#416] fix(library)!: use event-based approach to emit YAML

- library/src/main/kotlin/it/krzeminski/githubactions/domain/Workflow.kt
- library/src/main/kotlin/it/krzeminski/githubactions/dsl/WorkflowBuilder.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
Sometimes it's desired to run the whole workflow conditionally. Before
this change, it was only possible to define conditons for jobs defined
by the user. After this change, it's also possible to conditionally
disable the consistency job, so effectively it will be possible to omit
running the whole workflow.
> [#428] feat(library): add ability to conditionally run consistency job

- buildSrc/src/main/kotlin/buildsrc/convention/dsl-publishing.gradle.kts
A follow-up after the commit with major rename.
> [#462] fix: adjust library name for publishing

- .github/workflows/actions-versions.main.kts
- .github/workflows/actions-versions.yaml
- wrapper-generator/build.gradle.kts
> [#526] fix(wrapper-generator): fix reading 'actions' dir when suggesting versions

- library/build.gradle.kts
With the latest version of the plugin `binary-compatibility-validator` I can't do even a `./gradlew help`
> Could not download binary-compatibility-validator-0.12.1.jar (org.jetbrains.kotlinx:binary-compatibility-validator:0.12.1)
https://scans.gradle.com/s/ymfeu563hrxfc/failure#1
> build: fix plugin version

- library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
JRE 11 is the default one in the Ubuntu image of GitHub Actions runner. It's wrong since we started compiling to JRE 17 bytecode. Let's use 17 explicitly.
> [#605] fix(library): use JRE 17 in consistency check job

- library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
It intuitively makes sense to have a collection of jobs (for workflows) and a collection of steps (for jobs) as very last items. It's unlikely for `_customArguments` to contain values that would be a better fit for last attributes.
> [#623] fix(library)!: put jobs and steps as last attributes

- automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
- automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
In practice, action owners also use branches to keep references to major versions. GitHub accepts it because it's just another kind of reference, that's why both tags and branches work.
Closes #250.
> [#250] fix(wrapper-generator): look also on branches when suggesting new versions

- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm.gradle.kts
By specifying it, it enforces contributors to have it installed. It's possible to install it quickly using Gradle Toolchains, but still there is no reason to enforce any specific vendor. Let's remove it for simplicity.
Triggered by https://kotlinlang.slack.com/archives/C02UUATR7RC/p1674164513261249
> chore(library): don't specify JVM vendor

- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm.gradle.kts
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
The library doesn't really need any features that aren't present in Java 11. Thanks to this simplification, the consistency check job becomes faster again thanks to no need to set up another Java - Java 11 is available by default on GitHub Actions runners.
> [#637] fix(library)!: go back to using JRE 11

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
It will no only help find certain bugs, but will also fail if the workflows
use outdated action versions.
> ci: fail on warnings in Kotlin scripts

- library/api/library.api
- library/src/main/kotlin/it/krzeminski/githubactions/dsl/Preamble.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/Preamble.kt
- library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
- library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
- Do not add trailing whitespace in preamble
- Allow to insert the original preamble in a custom preamble
The placeholder name / form could be discussed.
I got inspired by lazy JSF EL expressions and dynamic Spock test names.
Something with `$` is bad, as it is a pita to escape in raw strings.
> Custom Preamble Improvements

- .github/workflows/_shared.main.kts
- .github/workflows/actions-versions.yaml
- .github/workflows/build.yaml
- .github/workflows/check-if-wrappers-up-to-date.yaml
- .github/workflows/release.yaml
- automation/typings/src/main/kotlin/it/krzeminski/githubactions/actionsmetadata/ActionsMetadataReading.kt
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm.gradle.kts
It's needed to synchronize the version with the Kotlin compiler. It's a prerequisite for using Gradle 8 (see #681).
Java 11 (and not some newer version) is used because its runtime is available without any extra
setup on GitHub Actions, so it makes it easier to use the library.
> chore(library): set Java version target to 11

- docs/user-guide/compensating-librarys-missing-features.md
- docs/user-guide/getting_started.md
- docs/user-guide/job-outputs.md
- docs/user-guide/type-safe-expressions.md
- docs/user-guide/using-actions.md
- library/build.gradle.kts
- library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/CompensatingLibrarysMissingFeaturesSnippets.kt
- library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/GettingStartedSnippets.kt
- library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/JobOutputsSnippets.kt
- library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/TypeSafeExpressionsSnippets.kt
- library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/UsingActionsSnippets.kt
- mkdocs.yml
Fixes: #195
Contentwise changes in the snippets:
- removed some trailing whitespace
- added an inline code highlighting
- replaced deprecated action with its current version
- fixed all the ktlint findings in the snippets
Everything else is currently identical to the previous outcome.
> docs: Extract snippets from documentation to tested files and fix invalid examples (#195)

- automation/typings/src/main/kotlin/it/krzeminski/githubactions/actionsmetadata/ActionsMetadataReading.kt
> [#719] fix(wrapper-generator): forbid unknown properties in typing YAML

- library/build.gradle.kts
- library/src/test/kotlin/io/github/typesafegithub/workflows/docsnippets/GettingStartedSnippets.kt
- mkdocs.yml
- script-generator/logic/src/main/kotlin/io/github/typesafegithub/workflows/scriptgenerator/Version.kt
`-SNAPSHOT` will be present in the version on `main` branch, and for releasing we'll remove the suffix.
> chore: set snapshot version 0.41.1-SNAPSHOT

- library/build.gradle.kts
- library/src/test/kotlin/io/github/typesafegithub/workflows/docsnippets/GettingStartedSnippets.kt
- mkdocs.yml
- script-generator/logic/src/main/kotlin/io/github/typesafegithub/workflows/scriptgenerator/Version.kt
It turned out that the latest version update was incorrect - I should have already bumped the minor version because I added some features.
> chore: update version to 0.42.0-SNAPSHOT

- buildSrc/src/main/kotlin/buildsrc/convention/dsl-publishing.gradle.kts
It makes it harder to work with them locally.
> chore(library): do not sign 'SNAPSHOT' versions

- .editorconfig
Motivation: https://kotlinlang.slack.com/archives/C02UUATR7RC/p1684128633483979?thread_ts=1684128633.483979&cid=C02UUATR7RC
> chore: configure .editorconfig to forbid star imports

- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/generation/Generation.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/generation/TextTransformation.kt
- library/src/gen/kotlin/io/github/typesafegithub/workflows/actions/gradle/GradleBuildActionV2.kt
They lead to having trailing whitespaces in the Kotlin code, which get removed by ktlint.
> feat(code-generator): remove trailing whitespaces from lines in descriptions

- library/src/test/kotlin/io/github/typesafegithub/workflows/docsnippets/GettingStartedSnippets.kt
- library/src/test/kotlin/io/github/typesafegithub/workflows/yaml/CaseTest.kt
It turned out that in ktlint version 0.50.0, `ktlint-disable` and `ktlint-enable`
are no longer supported. Renovate PR was merged because the CI job where
ktlint runs wasn't set as a required check. It has been fixed in GitHub
configuration, and now this fix is needed.
> fix: use @Suppress annotation to disable ktlint rules

- automation/action-binding-generator/api/action-binding-generator.api
- automation/action-binding-generator/build.gradle.kts
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ClassNaming.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/InputNullability.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/MetadataReading.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TextTransformation.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingGeneration.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingSuggestions.kt
The goal is to help polish the API so that no internally used stuff is exposed there,
only things strictly needed for bindings generation.
> [#941] chore(action-binding-generator): enable explicit API mode and dump API

- automation/action-binding-generator/api/action-binding-generator.api
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/InputNullability.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/MetadataReading.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TextTransformation.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingGeneration.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingSuggestions.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/types/TypesProviding.kt
This is the first step of making the API of action-binding-generator minimal. Some functions/classes are simply used just in this module, so can be made internal/private. The rest are unfortunately depended on from other modules, so these dependencies will need more effort to be sorted out.
> [#941] refactor(abg): hide trivial cases of impl details

- automation/action-binding-generator/api/action-binding-generator.api
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ClassNaming.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt
Thanks to this, the action binding generator doesn't have to expose a function that generates the class name - it's provided as a part of the generated binding object.
> [#941] refactor(automation): include class name in binding object

- library/build.gradle.kts
This way is the correct one to tell Gradle that other resources (outside of the standard `resources` dir) are used as inputs and outputs. In fact, it's only about `.github/workflows/Integration tests - *.yaml`, but for simplicity we mark the whole directory.
> test(library): fix adding extra resources

- .github/workflows/actions-versions.main.kts
- .github/workflows/actions/peterevans/CreateIssueFromFile.main.kts
It's an experiment towards ultimately having all action bindings generated and being used this way.
> [#941] chore(ci): use one action binding as imported source

- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingGeneration.kt
In the client-side binding generation, version in the action class name won't exist. This change makes it easier to introduce the main change by just controlling in a single place how the class name is built.
> [#941] refactor(abg): centralize building binding class name

- automation/action-binding-generator/api/action-binding-generator.api
- automation/action-binding-generator/build.gradle.kts
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerationTest.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProvidingTest.kt
- automation/code-generator/build.gradle.kts
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt
It's a step towards having the bindings generation process encapsulated within a single module: action-bindings-generator. Code-generator shouldn't be aware of this implementation detail.
> [#941] refactor: move typing resolving to abg

- docs/user-guide/nightly-builds.md
We're switching from JitPack to Sonatype snapshots because we now publish more than one artifact from this repo.
> [#774] docs: describe nightly builds using snapshots

- buildSrc/src/main/kotlin/buildsrc/convention/action-binding-generator-publishing.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/dsl-publishing.gradle.kts
- jitpack.yml
Now that we publish more than one artifact from this repo, JitPack is not suitable anymore. Instead, we publish Sonatype snapshots on each commit to main, and for feature branches, we can do it as well after a small code modification.
> [#774] chore: remove JitPack support

- automation/action-binding-generator/api/action-binding-generator.api
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/MetadataReading.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/MetadataRevision.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerationTest.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProvidingTest.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt
Before this change, the generator's API wasn't so explicit regarding which revision of the metadata will be fetched. Thanks to the new sealed hierarchy, it's now clear how the generator will behave.
> [#941] refactor(abg): enhance passing metadata revision

- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
It corresponds to reading locally available typings during bindings generation on the library side. Thanks to this, the client-side generation can benefit form them as well.
Ultimately the typings store (`actions/` directory) from github-workflows-kt will be probably moved to a separate repo.
> [#941] feat(abg): fetch typings maintained with library

- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerationTest.kt
It turned out that it's not necessary to add the dependency on the library or the shebang since the file isn't executed on its own, it's included by other scripts instead.
> [#941] fix(abg): adjust generated binding for script

- docs/user-guide/job-outputs.md
Referring by line numbers is prone to code snippets refactoring. It would be best to have the highlighting configured inline with the code, but I haven't found such option. Removing it for now seems to be better than presenting misleading highlight.
> docs: remove incorrect line highlighting

- automation/action-binding-generator/api/action-binding-generator.api
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ExtractUsedActionsFromWorkflow.kt
- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GitHubWorkflowModel.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ExtractUsedActionsFromWorkflowTest.kt
Thanks to this, the users will be able to have a YAML file a dummy workflow listing actions that they use in their Kotlin-based workflows, and then use this util function to generate required bindings.
This is not the final API, rather some part of the future plumbing that I'm exposing for now for experimentation.
> [#941] feat(abg): add util for generating bindings from workflow

- .github/workflows/actions-versions.yaml
- .github/workflows/used-actions.yaml
The goal is to test if Renovate works correctly for client-side binding generation.
> [#941] ci: deliberately downgrade version of action with generated binding

- .github/workflows/actions-versions.main.kts
- .github/workflows/generate-action-bindings.main.kts
The changes previously available only through snapshots are now released with 1.4.0.
> [#941] ci: use newly released 1.4.0 instead of snapshots

- library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
It's helpful to make the script generate bindings needed only by a
given workflow.
> [#941] feat(lib): add YAML file name as arg to bindings generation script

- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GitHubWorkflowModel.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ExtractUsedActionsFromWorkflowTest.kt
Other kinds of steps, e.g. with `run`, have to be parseable as well.
> [#941] fix(abg): support steps not only with 'uses' fields

- library/build.gradle.kts
- library/src/test/kotlin/io/github/typesafegithub/workflows/NonCompilableTest.kt
It's an updated fork of com.github.tschuchortdev:kotlin-compile-testing. Most importantly, it supports newer versions of Kotlin.
Needed as a prerequisite for #1066.
> chore(lib): switch from com.github.tschuchortdev:kotlin-compile-testing to dev.zacsweers.kctfork

- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ExtractUsedActionsFromWorkflow.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ExtractUsedActionsFromWorkflowTest.kt
Multiple usages of the same action in the same version were mistakenly
interpreted as more than one version used.
> [#1071] fix(abg): fix false error in extracting used actions

- .github/workflows/generate-action-bindings.main.kts
The library now provides a helper function for implementing the logic required for bindings generation.
> [#1071] ci: use generateActionBindings helper

- docs/user-guide/migrating-to-client-side-bindings-generation.md
- mkdocs.yml
The feature is still in preview, so it's not mentioned in the getting started guide.
> [#1087] docs: document migrating to client-side binding generation

- library/src/test/kotlin/io/github/typesafegithub/workflows/dsl/expressions/ContextsTest.kt
It unfortunately doesn't work in multiline strings, that's why I didn't change anything in `IntegrationTest`.
In ordinary string literals though, it does, and I believe it's a bit cleaner.
> Replace $dollar with \$ in ordinary string literals

- automation/typings/src/main/kotlin/io/github/typesafegithub/workflows/actionsmetadata/ActionsMetadataReading.kt
It's needed because once we remove e.g. some action-types.yml, certain directories wouldn't be tracked by git anymore, and we wouldn't generate these actions. Having a file with a well-defined name will let us drive the generation in a robust way.
> feat(code-generator): add new placeholder for actions

- automation/typings/src/main/kotlin/io/github/typesafegithub/workflows/actionsmetadata/ActionsMetadataReading.kt
- automation/typings/src/main/kotlin/io/github/typesafegithub/workflows/actionsmetadata/model/ActionBindingRequest.kt
Part of #1072.
They are not needed anymore - the action bindings generator can already fetch them
either from the action itself, or from the typings catalog.
> refactor(automation): stop reading local action typings

- build.gradle.kts
Part of #890.
It needs to be fixed to work with Gradle configuration cache.
> chore: fix task setting is-snapshot flag

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
- .github/workflows/release.main.kts
- .github/workflows/release.yaml
Part of #890.
These tasks contain elements that make them not compatible with configuration caching. It will likely be fixed in the future.
> ci: disable Gradle configuration cache for releasing tasks

- automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
- automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerationTest.kt
Part of #1151.
It's needed to have forward compatibility, i.e. to let the typings reflect some newer version of the action, and still using a bit older action manifest (action.yml).
https://github.com/typesafegithub/github-workflows-kt/actions/runs/7044641012
> fix(automation): allow having non-existent fields in typings

- .github/workflows/release-common.main.kts
- .github/workflows/release-docs.yaml
- .github/workflows/release.yaml
Part of #1174.
Apparently Dokka doesn't support Gradle configuration cache yet.
> fix(ci): do not use Gradle config cache with Dokka

- settings.gradle.kts
"...-root" looks weird in the project picker view in IntelliJ. Monorepo expresses the intent better.
> chore: rename root project to '...-monorepo'

- automation/code-generator/build.gradle.kts
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/ActionBindingsToGenerate.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/ActionsDocsGeneration.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/ActionsMetadataReading.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/AddDeprecationInfo.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/model/ActionBindingRequest.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/model/Version.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/Http.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersions.kt
- automation/code-generator/src/test/kotlin/io/github/typesafegithub/workflows/codegenerator/AddDeprecationInfoTest.kt
- automation/code-generator/src/test/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersionsTest.kt
- automation/typings/README.md
- automation/typings/build.gradle.kts
- automation/typings/src/main/kotlin/io/github/typesafegithub/workflows/actionsmetadata/ActionBindingsToGenerate.kt
- settings.gradle.kts
There's no point in keeping this module separate, now that we moved the typings to github-actions-typing-catalog.
> refactor: consolidate 'typings' module into 'code-generator'

- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProvidingTest.kt
Fixes #1073.
If there's no typings for a given version in the catalog, typings for an older version is tried to be fetched. Thanks to this, we cover a scenario where usually the next version of some action doesn't need to have typings defined immediately because the older version is fine. It doesn't account for breaking changes where this approach will produce an incorrect binding, however in practice it should be better than what we have now.
It doesn't hold for action-hosted typings.
> feat(abg): use typings for older version if available

- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/dsl/JobBuilder.kt
- github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt
> fix(gwkt): allow script names with spaces for Kotlin-based steps

- action-binding-generator/api/action-binding-generator.api
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerateActionBindingsCliHelper.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
Part of #1318.
Thanks to this, we'll be able to define yet another mode, optimized for hosting the JARs with bindings by a dedicated service.
> feat(abg): create enum for binding generation modes

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
Per the docs: https://github.com/gradle/actions/tree/main/setup-gradle#saving-configuration-cache-data
This is the only missing element.
> fix(ci): use Gradle encryption key for storing configuration cache

- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Utils.kt
Before this change, if the generated Kotlin file didn't match the expected one, a new file was created under a different path. It was then hard to just accept the changes i.e. use what was actually produced as the expected file. This change makes the test edit the file in place.
> test(abg): update generated file in place

- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionForGeneratedJar.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputsV3.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
It turned out that referring to some class in Kotlin Poet doesn't work correctly for the JAR consumer.
> fix(abg): correctly generate binding for JAR if some output present

- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt
Part of #1318.
There's no need to override this because the class's objects are used
as values, not as map/set keys.
> refactor(server): simplify JarArtifact class

- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
> fix(server): return only major versions in maven-metadata.xml

- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PomBuilding.kt
Part of #1318.
Mentioning github-workflows-kt's URL in action binding's POM is a bad
idea, it makes Renovate think that this Maven package is a part of
github-workflows-kt monorepo which is wrong.
Also removing some unneeded fields.
> fix(server): adjust POM to work with Renovate

- .github/workflows/test-script-consuming-jit-bindings.main.do-not-compile.kts
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt
Part of #1318.
It doesn't yet support enumerating specific versions for e.g. dependency
updating bots.
> feat(server): serve artifacts for specific versions

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
It makes the test catch a case when the endpoint returns HTTP 200, but the contents is malformed.
> test(server): ensure maven-metadata.xml returns existing version

- automation/code-generator/build.gradle.kts
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/ActionsDocsGeneration.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/AddDeprecationInfo.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/Http.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersions.kt
- automation/code-generator/src/test/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersionsTest.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/model/Version.kt
A step towards having fetching available action versions in shared-internal.
> refactor: move Version to shared-internal

- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/Http.kt
- automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersions.kt
- jit-binding-server/build.gradle.kts
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubUtils.kt
A step towards having fetching available action versions in shared-internal.
> refactor: move getGithubToken to shared-internal

- buildSrc/src/main/kotlin/buildsrc/convention/publishing.gradle.kts
this makes it so you can run `publishToMavenLocal` without signing
even when `sign()` is not being called the plugin is stil ldoing something and erroring when the environment is not set up correctly
the issue turns out to be `project.version` not being defined until later
~~the task being used as a condition is probably not correct and this can be adjusted, we could instead check for the absence of `publishToMavenLocal` ?~~
we don't need this check anymore
> chore: skip signing for snapshot versions

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
It's simply not needed as signing doesn't happen there.
> chore: remove signing keys from snapshot publishing job

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
- .github/workflows/end-to-end-tests.main.kts
- .github/workflows/end-to-end-tests.yaml
- github-workflows-kt/build.gradle.kts
The main goal of this workflow is to use freshly build library from
a given commit inside a workflow ran from a Kotlin script.
> ci: add end-to-end tests workflow

- github-workflows-kt/api/github-workflows-kt.api
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/contexts/GithubContext.kt
There was no default value assigned, so in fact it was required in the
JSON.
> fix(dsl): make 'after' github context field optional

- .github/workflows/end-to-end-tests.main.kts
- build.gradle.kts
- docs/user-guide/getting_started.md
- github-workflows-kt/api/github-workflows-kt.api
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
- github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/docsnippets/GettingStartedSnippets.kt
- mkdocs.yml
Part of #1208.
There's going to be a single way of writing the YAML to file. In practice, it turned out that `toYaml()` is used very sparingly.
> chore(dsl)!: remove toYaml()

- github-workflows-kt/api/github-workflows-kt.api
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilder.kt
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
- github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt
Closes #1468.
It was possible in 1.x, and this possibility was removed because I assumed no one needs it. It turns out that some users prefer writing the YAML themselves. This simple backward-compatible change gives more freedom to the users of the lib.
> feat(dsl): allow writing workflow to string

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
Part of #1492.
In the next change, we'll add alternative routes with the same logic, i.e. without the leading `/binding`. Later on, once we migrate all known usages, `/binding` will be removed.
> refactor(server): extract handlers in routing to functions

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
- .github/workflows/test-script-consuming-jit-bindings-old.main.do-not-compile.kts
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
Part of #1492.
It adds an alternative routing, without the `/binding` part, thanks to which the user-facing URL will be shorter and nicer.
> feat(server): add routing without '/binding'

- .github/workflows/actions-versions.main.kts
- .github/workflows/bindings-server.main.kts
- .github/workflows/build.main.kts
- .github/workflows/check-if-action-bindings-up-to-date.main.kts
- .github/workflows/create-action-update-prs.main.kts
- .github/workflows/gradle-wrapper-validation.main.kts
- .github/workflows/release-common.main.kts
- .github/workflows/release-docs.main.kts
- .github/workflows/release.main.kts
- .github/workflows/setup-java.main.kts
- .github/workflows/setup-python.main.kts
- .github/workflows/test-script-consuming-jit-bindings-old.main.do-not-compile.kts
- .github/workflows/test-script-consuming-jit-bindings.main.do-not-compile.kts
- buildSrc/src/main/kotlin/buildsrc/tasks/AwaitMavenCentralDeployTask.kt
- docs/user-guide/migrating-to-Maven-based-bindings.md
It's the new one, used e.g. in Gradle in `mavenCentral()` function.
> chore: use new URL for Maven Central

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
- .github/workflows/test-served-bindings-depend-on-library.main.do-not-compile.kts
- MAINTENANCE.md
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PomBuilding.kt
Thanks to this, one doesn't have to explicitly depend on the library if a given script uses only the binding. It saves one `@file:Repository` line from the user's script.
> fix(server): add dependency on library in action binding JAR

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
It's because whenever a deployment happens, there's a short downtime. The problem is not yet solved, so as a workaround, let's deploy in a controlled manner (and not e.g. at every Renovate update), at a time where little traffic should flow (Sunday, midnight UTC).
> chore(ci): deploy only on Sunday or on demand

- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithFancyCharsInDocsV3.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
Fixes #1562.
Percent sign is used by KotlinPoet for placeholders, see https://square.github.io/kotlinpoet/1.x/kotlinpoet/kotlinpoet/com.squareup.kotlinpoet/-code-block/index.html
> fix(abg): allow using percent sign in action API description

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
Because of this bug, some entry could live forever, until the next server restart, because each access would effecively prolong their life in the cache by 1 hour. It's undesirable - we want to treat the cached bindings as if they were valid since their generation for 1 hour.
> fix(server): evict cache entry after 1 hour of write, not access

- .github/workflows/end-to-end-tests.main.kts
- .github/workflows/end-to-end-tests.yaml
The action doesn't have `generate-job-summary` input anymore.
I prematurely force-merged this PR: https://github.com/typesafegithub/github-workflows-kt/pull/1577 - it would be caught there!
> fix(ci): remove non-existing input from action in end-to-end tests

- action-binding-generator/api/action-binding-generator.api
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
Part of #1585.
Thanks to this, we'll be able to return e.g. `Checkout` and `Checkout_Untyped` classes in a single JAR.
> refactor: prepare for generating more than one binding class

- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Utils.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
Part of #1585.
This way these assertions will hold true if we add generation of
untyped binding.
> test(abg): refactor assertion on the generated binding

- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
Part of #1585.
It's needed because without this change, the generator infers there are no typings for these test actions (the actions actually don't exist), and in the new world it would only produce the `_Untyped` binding for them. These tests actually check the path where the typings are provided. For simplicity, we use `String` everywhere because there's already a test that checks generation for other typings.
> test(abg): specify typing in generation test

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
All compilations happen on the same machine, and share the contents of `~/.m2` directory. If we don't clean it, we reuse fetched libraries from previous compilations. It's undesired because e.g. the main script was compiled with the prod bindings server, but next compilations use a server instance started locally.
> test: clean Maven Local before compiling scripts in server tests

- .github/workflows/test-script-consuming-jit-bindings.main.do-not-compile.kts
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/metadata/InputNullability.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputsTest.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputs_Untyped.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithFancyCharsInDocs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithInputsSharingType.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoInputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithOutputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithPartlyTypings.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithPartlyTypings_Untyped.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithSomeOptionalInputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/SimpleActionWithRequiredStringInputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/metadata/InputNullabilityTest.kt
- docs/user-guide/migrating-to-Maven-based-bindings.md
- docs/user-guide/using-actions.md
Fixes #1585
I have to confess, that I did not check every change in the unit test workflow files,
so they should probably be looked again closely. But I think it should have done the right thing.
Or at least how I envisioned it.
no typing =>
- only `_Untyped` class with `_Untyped` properties
- nullability according to required status
full typing =>
- same `_Untyped` class as above
- but marked as `@Deprecated` with a replace hint for the typed class (works in the IDE),
- additionally a typed class with each property as typed and untyped version
- all properties nullable, with runtime checks that
- not the typed and untyped is set both for one property
- one of the two is set for required properties
partly typing =>
- same `_Untyped` and typed class as above
- for inputs that have no type …
> feat(abg)!: provide untyped fields always and typed ones if type available

- .github/workflows/test-script-consuming-jit-bindings.main.do-not-compile.kts
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputsTest.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputs_Untyped.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithDeprecatedInputAndNameClash.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithFancyCharsInDocs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithInputsSharingType.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoInputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoTypings_Untyped.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithOutputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithPartlyTypings.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithPartlyTypings_Untyped.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithSomeOptionalInputs.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/SimpleActionWithRequiredStringInputs.kt
Fixes #1626.
A long-term approach is tracked in https://github.com/typesafegithub/github-workflows-kt/issues/1629.
> fix(abg): reinstate public copy method in binding classes

- README.md
- docs/index.md
Be more clear about the "two-step approach" that still requires YAML files to be generated underneath, which serve as the definition of workflows. This should help to avoid the impression that the project can be used as a complete substitute for using YAML files at all.
> docs: clarify that still YAML files are generated

- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/model/Version.kt
This makes the metadata file content more stable and allows to provide a checksum,
as Kotlin for example is quite unhappy if it finds no checksum or cannot successfully verify it.
Without this every request would produce a different file and thus also a different checksum file,
so the checksum would never match the file contents.
> fix(abg): use the release date of the latest version for lastUpdated

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt
In some cases, only e.g. a POM is necessary to fetch for a given action. Thanks to this change, no Kotlin compilation or JAR creation will happen when requesting an artifact that doesn't require it.
> perf(abg): create JARs only when they are actually requested

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/OpenTelemetryConfig.kt
Previously, the OpenTelemetry metric and log record exporters were initialized without specifying an endpoint. This change sets the endpoint configuration for both exporters to ensure they communicate with the correct server.
Without this change, the default endpoint is `localhost`, which won't resolve and thus part of the payload won't be published. This leads to a
complete failure of metric/telemetry publishing, and it's the reason
why many metrics are not making their way into Jaeger.
Making the change and running the docker repository locally proved to me
that no more errors were showing up in the log. Next step is bringing
it to production
> fix(server): configure endpoint for OpenTelemetry exporters

- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt
Fixes #1667.
In the logic, we were trying to parse version like `v2-beta` into an
integer. We could generally try to do it, but I think there are too
many possible variations to support them, so let's just support
versions that after removing the leading `v`, gives us an integer.
> fix(abg): handle non-numeric versions gracefully

- action-binding-generator/api/action-binding-generator.api
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/domain/ActionCoords.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/ClassNaming.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/metadata/MetadataReading.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithSubAction.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/ClassNamingTest.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/ActionCoordsUtils.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/ModuleBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PackageArtifactsBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PomBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt
Before these changes, `ActionCoords#name` sometimes had the actual action coordinates, so for example `some-name__some-sub`, sometimes it had the replaced `some-name/some-sub`.
This is not good, as you never know what you get and also led to certain bugs where wrong things are written to metadata files for example.
This changes unifies the situation, so that the `name` only contains the repository name and the `path` is in a separate property with slashes.
All other manipulation is then done where needed.
> refactor: unify content of ActionCoords name

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
The goal is to fix restoring configuration cache, because otherwise we're getting:
```
Calculating task graph as configuration cache cannot be reused because an input to task ':buildSrc:compilePluginsBlocks' has changed.
```
> chore(ci): cache buildSrc/build dir

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/OpenTelemetryConfig.kt
We're about to change a service which receives the traces. It's now
Jaeger, and thanks to this change: https://github.com/LeoColman/MyStack/pull/21,
Jaeger is now reachable by the more abstract host name. It lets us
abstract out what component receives the traces by simply configuring
in Docker Compose's config which service will be available under this
hostname. Ultimately, it will allow us to enable aggregated metrics with
OTel Collector and Prometheus without downtime.
> chore(server): change tracer collector's host name

- action-binding-generator/build.gradle.kts
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt
kaml added proper support for configuring enablement of anchors and aliases. It's possible to remove the workaround of directly using snakeyaml-engine-kmp, and while here, depend on a sane default of 100 max aliases.
> chore(abg): remove custom billion laughs attack protection

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
Part of #1756.
The goal here is to both depict the current behavior, but also save us from unintentionally having Renovate auto-merge PRs that bump Kotlin version, which results in having incompatibility in Kotlin Metadata. The details of the problem are described in #1756.
> test(server): add test for using older Kotlin compiler

- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PackageArtifactsBuilding.kt
Part of https://github.com/typesafegithub/github-workflows-kt/issues/1774.
It doesn't fix the entire issue because we should be able to see the major versions, even if they don't have the `v` in front, because such versions are consumable as action bindings. This change just prevents the failures of the server.
> fix(server): return 'not found' for maven-metadata.xml if no major version found

- github-workflows-kt/api/github-workflows-kt.api
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/triggers/Release.kt
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/TriggersToYaml.kt
- github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/domain/triggers/OtherTriggersTest.kt
Closes https://github.com/typesafegithub/github-workflows-kt/issues/1781
> feat(library): add 'type' argument to Release trigger

- github-workflows-kt/api/github-workflows-kt.api
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/Step.kt
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/dsl/JobBuilder.kt
- github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/domain/StepTest.kt
- github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/yaml/StepsToYamlTest.kt
Part of https://github.com/typesafegithub/github-workflows-kt/issues/1780.
It will help us provide cleaner API for describing a step outside of the `job` DSL function.
> refactor(library): move building step outputs to ActionStep

- github-workflows-kt/api/github-workflows-kt.api
- github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/triggers/WorkflowDispatch.kt
- github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/yaml/TriggersToYamlTest.kt
Technically a breaking change for anyone that relies on enum's exhaustiveness, but I think such usage is highly unlikely.
> feat(library): add 'number' as input type of WorkflowDispatch

- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/ActionTypes.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt
Part of https://github.com/typesafegithub/github-actions-typing/issues/253.
A similar change was done in https://github.com/typesafegithub/github-actions-typing/pull/265.
> feat(server): allow empty inputs and outputs in typings

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ActionCoords.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/InternalRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Plugins.kt
This PR prepares the ground to add metrics by refactoring the code to enhance metric-attachment-points.
> refactor(server): split ktor config into separate files

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
The when expression is now exhaustive and the compiler can imply that the else branch is never reached.
This commit removed the useless else branch without changing any functionality.
> chore(server): remove unnecessary else branch on ArtifactRoutes

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
As commented in https://github.com/typesafegithub/github-workflows-kt/pull/1824#discussion_r1955700775, the status metrics is not obtained because we try to get it before
the call happens.
This commit adjusts that by placing the metric increment to be after the
call is processed.
> fix(server): move registering artifact metrics to after call response

- shared-internal/src/test/kotlin/io/github/typesafegithub/workflows/shared/internal/model/VersionTest.kt
It reveals a bug found by @Vampire and being fixed in https://github.com/typesafegithub/github-workflows-kt/pull/1831. This PR adds proper, direct visibility to the current behavior.
> test: add test for parsing version components

- jit-binding-server/build.gradle.kts
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
In order to have a better monitoring of our cache, a library that easily
exposes metrics is a requirement.
This commit replaces the current cache implementation with Aedile, a wrapper to Caffeine.
Caffeine supports monitoring natively, while aedile allows us to access it without losing the kotlin-like style.
> feat(server): replace cache library with Aedile

- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
- maven-binding-builder/src/test/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuildingTest.kt
Related to https://github.com/typesafegithub/github-workflows-kt/pull/1611.
We're going to make some changes in the function, so let's add some safety net to prevent regressions + a way to see how the modified function behaves.
> test(server): add tests for Maven metadata building

- .github/workflows/test-script-consuming-jit-bindings.main.do-not-compile.kts
- action-binding-generator/api/action-binding-generator.api
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/domain/ActionCoords.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/domain/SignificantVersion.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoInputsWithMajorVersion.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoInputsWithMajorVersion_Untyped.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoInputsWithMinorVersion.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoInputsWithMinorVersion_Untyped.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/ClassNamingTest.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt
- docs/user-guide/using-actions.md
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ActionCoords.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/ActionCoordsUtils.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
- maven-binding-builder/src/test/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuildingTest.kt
- mkdocs.yml
With these changes you can for example depend on `actions:cache__save___major:[v4,v5)"` and get the latest v4 action with latest v4 typing by resolving to a concrete v4.x.y version but the output still contains just `v4`.
The same for `actions:cache__save___minor:[v4.0,v4.1)`, to get the latest v4.0 but in the output just have `v4.0`.
> feat: allow using version ranges to cope with stale Maven Local cache

- action-updates-checker/src/main/kotlin/io/github/typesafegithub/workflows/updates/Utils.kt
- maven-binding-builder/build.gradle.kts
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
- maven-binding-builder/src/test/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuildingTest.kt
- shared-internal/build.gradle.kts
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
- shared-internal/src/test/kotlin/io/github/typesafegithub/workflows/shared/internal/model/GithubApiTest.kt
Part of https://github.com/typesafegithub/github-workflows-kt/issues/1855.
This PR also adds graceful handling of non-success responses from GitHub: instead of exceptions we started using Arrow Kt and `Either`.
> fix: display full response and don't fail if GitHub responds with non-success

- action-updates-checker/src/main/kotlin/io/github/typesafegithub/workflows/updates/Reporting.kt
- action-updates-checker/src/main/kotlin/io/github/typesafegithub/workflows/updates/Utils.kt
- action-updates-checker/src/test/kotlin/io/github/typesafegithub/workflows/updates/ReportingTest.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PackageArtifactsBuilding.kt
- maven-binding-builder/src/test/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuildingTest.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubUtils.kt
- shared-internal/src/test/kotlin/io/github/typesafegithub/workflows/shared/internal/model/GithubApiTest.kt
Part of https://github.com/typesafegithub/github-workflows-kt/issues/1854.
A "GitHub token" is, I think, a reserved name for a special kind of token. With this change we'd like to express that the code can work with various kinds of token that can be used to call GitHub's API, not necessarily what is available under `GITHUB_TOKEN` and created by GitHub, or not necessarily a Personal Access Token. In particulr, we're working on switching to authenticating with a custom GitHub app where we'll have Applicaiton Installation Token.
> chore: rename githubToken to githubAuthToken

- .github/workflows/release.main.kts
- .github/workflows/release.yaml
- github-workflows-kt/build.gradle.kts
- gradle.properties
In Dokka 2.1.0, the V1 mode will be gone. Opting in proactively, and to get rid of annoying warnings.
> chore: migrate to Dokka plugin V2

- jit-binding-server/src/main/resources/log4j2.xml
Trace lines by default are printed black which on a dark background is nearly unreadable unless you select the lines.
With this change we print them magenta instead which is readable on dark and light backgrounds properly
> chore(server): use magenta for trace log lines

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
Per https://kotlinlang.slack.com/archives/C02UUATR7RC/p1743596200759679?thread_ts=1742907721.287939&cid=C02UUATR7RC:
> Watchtower enabled for our container only. Let's see how it goes.
> Updates should happen as soon as the docker image is created in
> dockerhub and the webhook is no longer necessary (probably worked
> only as a placebo anyways)
We can remove this webhook calling (that doesn't work anyway) and rely on periodic image pulls by Watchtower.
> chore(ci): remove triggering server image pull

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GitHubApp.kt
Thanks to this, it's easier to test with different client ID and installation ID - no code changes are required.
Per @Vampire's request: https://kotlinlang.slack.com/archives/C02UUATR7RC/p1743494744804909?thread_ts=1742907721.287939&cid=C02UUATR7RC
> feat(server): allow configuring client ID and installation ID vial env vars

- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubUtils.kt
- Attempts to retrieve a GitHub App Installation token first
- Falls back to GITHUB_TOKEN if the installation token fails
- Logs a warning on failure of installation token retrieval
- Updated KDocs for both getGithubAuthToken and getGithubAuthTokenOrNull
> feat(server): add fallback to GITHUB_TOKEN if installation token fails

- shared-internal/build.gradle.kts
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GitHubApp.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubUtils.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/model/Version.kt
Motivated by ability to detect redundant `suspend` modifier: https://detekt.dev/docs/rules/coroutines/#redundantsuspendmodifier, see https://github.com/typesafegithub/github-workflows-kt/pull/1889/files#r2030503149.
> chore(shared-internal): add detekt linter

- shared-internal/build.gradle.kts
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GitHubApp.kt
- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubUtils.kt
Part of https://github.com/typesafegithub/github-workflows-kt/issues/1884.
Simplified access token handling by leveraging `org.kohsuke:github-api` library, removing custom HTTP client and serialization logic.
> refactor: replace custom HTTP client with GitHub API library when fetching installation token

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
So that we don't have to maintain the version of Windows, like suggested in https://github.com/typesafegithub/github-workflows-kt/pull/1896.
> chore(ci): use windows-latest instead of specific version in tests

- shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/PathUtils.kt
Closes https://github.com/typesafegithub/github-workflows-kt/issues/1898.
`findGitDir` function is used to figure out where the script is run from, so it's a critical function that is called upon each YAML regeneration.
The check if it's a directory causes troubles when using git's worktrees. `.git` is a symlink to the real `.git` dir, so it's not a directory. Based on https://github.com/typesafegithub/github-workflows-kt/issues/1898#issuecomment-2806850958.
> fix(library): do not check if .git is a dir

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt
To improve testability, for the purpose of testing the fix in https://github.com/typesafegithub/github-workflows-kt/pull/1924
> refactor(server): allow not passing Prometheus registry to most routes

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt
To improve testability, for the purpose of testing the fix in https://github.com/typesafegithub/github-workflows-kt/pull/1924
> refactor(server): allow injecting bindings cache

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
- jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutesTest.kt
Before this PR, it was treated equally if a binding could not be found,
and if some exception happened during initial creating of the binding.
The exceptions were swallowed and the client received a 404 response.
If there was for example a compile error you already got internal server error.
But if for example Kotlin Poet throws an illegal argument exception,
then this did not propagate properly
Now exceptions are logged and the client gets an internal server error
if some exception happened and only a 404 if indeed the action was not found.
One such example is, if a typing has an `enum` with some option that contains a colon.
This resulted in an identifier generated that contains a colon which then produces an
exception due to the illegal identifier character.
> fix(server): treat failed binding generation as internal server error

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutesTest.kt
Thanks to this, the test aren't aware of an implementation detail of the server: the cache.
We wrap the whole server config in an `appModule`, and inject a piece of logic exposed by `maven-binding-builder` Gradle module. This piece is the only thing we need to mock right now in the test. It makes the test less brittle and couple with the implementation (although some necessary coupling is still there).
> refactor(server): do not leak cache in tests

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt
Part of https://github.com/typesafegithub/github-workflows-kt/issues/1938.
We're going to get rid of `Result` in the type, so it makes sense to call the alias in a more generic way.
> refactor(server): rename typealiases for cached objects

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt
- jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutesTest.kt
- jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutesTest.kt
Resolves https://github.com/typesafegithub/github-workflows-kt/issues/1938.
Before this change, if there was a failure during binding generation which result in an exception, it was actually cached and returned to the user for the next hour.
This change causes the server to not cache the failure, and instead let the user retry.
> fix(server): don't cache artifact generation failure

- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
- jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
- jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutesTest.kt
- jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutesTest.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt
This refactoring is necessary because we're going to add another piece of info returned from binding generation.
> refactor(server): add wrapping type for version artifact results

- .github/workflows/end-to-end-tests.main.kts
- .github/workflows/end-to-end-tests.yaml
This PR attempts to better capture the current current incorrect behavior for `Contexts.env`.
Part of https://github.com/typesafegithub/github-workflows-kt/issues/1956.
> test(library): add basic assertion for env context's tests

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
I noticed some flakiness in the tests, in fetching bindings. Let's add some basic observability to enable troubleshooting.
> ci: print server logs after server tests

- action-binding-generator/api/action-binding-generator.api
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/domain/ActionTypings.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/ActionTypes.kt
- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoInputsFromFallbackVersion.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt
This should hopefully improve on https://slack-chats.kotlinlang.org/t/28511490/hi-i-might-have-a-similar-problem-as-leonardo-had-https-kotl#8c8c2a6c-f008-4184-a8b7-25620530191d, at least notifying users by a deprecation note that fallback typings are used and that they might have to clear the cache to get updated typings and also nudge them to update the catalog typings.
> feat(abg): mark typed bindings from fallback version as deprecated

- buildSrc/build.gradle.kts
Gradle usually lags behind newest Kotlin version, more or less. Let's try tracking the newest Kotlin version used for the Kotlin DSL in Gradle.
> chore(deps): use the same Kotlin version for Gradle

- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm-server.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm.gradle.kts
Necessary because when updating to Kotlin 2.2.0, the build starts failing.
> chore: migrate off of deprecated kotlinOptions API

- .github/workflows/bindings-server.main.kts
- .github/workflows/bindings-server.yaml
- maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
Thanks to this, consumer that use older Kotlin version may use the bindings server. The oldest compatible version is 1.9.0.
Part of https://github.com/typesafegithub/github-workflows-kt/issues/1756.
> feat: produce bindings with 2.0 Kotlin target

- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt
- action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt
`IOException` is a very broad type that can occur in case of network problems. Then, interpreting as "the file is not found" impacts the correctness. Let's change it to `FileNotFoundException`.
> fix(server): fix exception type meaning YAML was not found

- action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt
Part of https://github.com/typesafegithub/github-workflows-kt/issues/2025.
This is just cleanup and removing excess calls that don't make sense anymore.
> chore(server): fetch typings from catalog only from lowercased owner/name

- docs/faq.md
The issue has been fixed: https://youtrack.jetbrains.com/issue/KTIJ-14580 and is waiting to be released in IntelliJ IDEA 2025.2 ([ref](https://kotlinlang.slack.com/archives/C0BT46EL8/p1751382806878189?thread_ts=1751159849.234259&cid=C0BT46EL8)).
> docs: remove issue related to no support for imports in IntelliJ

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
Warnings often appear when actions do not have typings for a new major version. Let's be less strict here.
> chore(ci): do not treat warnings as errors in Kotlin scripts
