library/src/main/kotlin/it/krzeminski/githubactions/domain/triggers/WorkflowDispatch.kt
library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
library/src/test/kotlin/it/krzeminski/githubactions/yaml/TriggersToYamlTest.kt

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs

[#64] WorkflowDispatch Inputs

---

library/src/gen/kotlin/it/krzeminski/githubactions/actions/actions/SetupNodeV2.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/metadata/MetadataReading.kt
wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/wrappersfromunittests/SimpleActionWithRequiredStringInputsV3.kt

Deprecated properties based on the field `input.deprecationMessage`
https://github.com/actions/setup-node/blob/f099707f6e7a91b89cdebdeca599fc76cc8bf088/action.yml#L33

generation: deprecated properties

---

wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt

Detect typos on input names inside `WrappersToGenerate.kt`

generation: invalid properties

---

library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt

Co-authored-by: nikky <git@nikky.moe>

ToYaml: simplify slashes normalization

---

library/src/gen/kotlin/it/krzeminski/githubactions/actions/10up/ActionWordpressPluginDeployV2.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/8398a7/ActionSlackV3.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/DockerLoginV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/LoginV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/WebappsDeployV2.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/borales/ActionsYarnV2.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/googlecloudplatform/GithubActionsV0.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/jamesives/GithubPagesDeployActionV4.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/jasonetco/CreateAnIssueV2.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/samkirkland/FTPDeployActionV4.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

I added the definitions of all the wrapper requests in `WrappersToGenerate.kt` but enabled only the first ten

[#95] Add wrapper requests for popular actions

---

wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/metadata/MetadataReading.kt

Log the URL of the YAML file so we can more easily check whether the typings are good
```
> Task :wrapper-generator:run
Generating ActionCoords("actions", "cache", "v2") from https://raw.githubusercontent.com/actions/cache/v2/action.yml
Generating ActionCoords("actions", "checkout", "v2") from https://raw.githubusercontent.com/actions/checkout/v2/action.yml
```

generator: log URL of yaml file

---

wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

Keep order of action wrappers sorted

---

.github/workflows/_GenerateWorkflows.main.kts
.github/workflows/check-if-wrappers-up-to-date.main.kts
.github/workflows/check-if-wrappers-up-to-date.yaml
library/src/gen/kotlin/it/krzeminski/githubactions/actions/googlegithubactions/SetupGcloudV0.kt

This is an extra check to ensure that the wrappers and the code
describing what wrappers are needed are both in sync.

chore(ci): Check if wrappers are up to date

---

jitpack.yml

needs some section to be added to docs, how to use nightly builds in `.main.kts` scripts:
```
@file:Repository("https://jitpack.io")
@file:DependsOn("com.github.krzema12:github-actions-kotlin-dsl:main-SNAPSHOT")
```

[#135] add jitpack.yml

---

library/src/gen/kotlin/it/krzeminski/githubactions/actions/adm/GithubPushActionV0.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/anmol098/WakaReadmeStatsV4.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/anothrnick/GithubTagActionV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/appleboy/ScpActionV0.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/appleboy/SshActionV0.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/appleboy/TelegramActionV0.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/awsactions/AmazonEcrLoginV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/awsactions/AmazonEcsDeployTaskDefinitionV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/awsactions/AmazonEcsRenderTaskDefinitionV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/awsactions/ConfigureAwsCredentialsV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/bahmutov/NpmInstallV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/cachix/InstallNixActionV17.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/calibreapp/ImageActionsV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/codecov/CodecovActionV3.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TypingSuggestions.kt
wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TypingSuggestionsTest.kt

Add 14 new wrapper actions

---

docs/supported-actions.md
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt

Hello, I optimized a bit how the "Supported Actions" look so that
- we have a direct link to the GitHub repo which has often very useful information
- we see the concrete Kotlin class name which is what we as Kotlin devs use

docs: improve Supported Actions

---

.github/workflows/_GenerateWorkflows.main.kts
.github/workflows/actions-versions.main.kts
.github/workflows/actions-versions.yml
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt

Depends on https://github.com/krzema12/github-actions-kotlin-dsl/pull/170

Workflow that creates an issue with available updates

---

docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/madhead/SemverUtilsV2.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

BREAKING action madhead/semver-utils@v2

---

library/src/main/kotlin/it/krzeminski/githubactions/domain/Concurrency.kt
library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
library/src/main/kotlin/it/krzeminski/githubactions/domain/Workflow.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/JobBuilder.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/WorkflowBuilder.kt
library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptgenerator/GitHubWorkflow.kt
script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptgenerator/Jobs.kt
script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptmodel/NormalizeYaml.kt
script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptmodel/YamlJob.kt
script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptmodel/YamlWorkflow.kt
script-generator/src/test/kotlin/generated/DockerImage.kt
script-generator/src/test/kotlin/generated/NodeJsPackage.kt
script-generator/src/test/kotlin/test/NormalizeYamlTest.kt
script-generator/yaml-input/docker-image.yml
script-generator/yaml-input/node-js-package.yml
script-generator/yaml-output/docker-image.yml
script-generator/yaml-output/nodejs-package.yml

Workflow.concurrency and Job.concurrency

---

.github/workflows/build.main.kts
.github/workflows/build.yaml
.github/workflows/release.main.kts
.github/workflows/release.yaml
docs/requirements.txt

Should catch some classes of mistakes in the docs or its config.

[#151] docs: build together with the library

---

library/src/gen/kotlin/it/krzeminski/githubactions/actions/gradle/GradleBuildActionV2.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

`cache-write-only` looks like a boolean.

feat(wrappers): update and fix typing for gradle/gradle-build-action@v2

---

.github/workflows/build.main.kts
.github/workflows/build.yaml

Currently: only GitHub workflows.

[#278] feat(ci): build Kotlin scripts

---

README.md

Help people to want to click on the documentation website
Made with https://carbon.now.sh
Code:
```kotlin
#!/usr/bin/env kotlin
// .github/workflows/github-action.main.kts
@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:VERSION")
workflow(
name = "GitHub Action workflow - but YAML free 🎉",
on = listOf(Push()),
sourceFile = __FILE__.toPath(),
) {
job(id = "my_job", runsOn = RunnerType.UbuntuLatest) {
uses(name = "Check out",      action = CheckoutV3() )
run( name = "Print greeting", command = "echo Hello world" )
}
}.writeToFile()
```

docs: teaseing with an image

---

docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/gautamkrishnar/BlogPostWorkflowV1.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

[#300] feat(wrappers): use v1 for gautamkrishnar/blog-post-workflow

---

docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/vampire/SetupWslV1.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TextTransformation.kt
wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TextTransformationTest.kt

[#299] feat(wrappers): add Vampire/setup-wsl@v1

---

library/build.gradle.kts
library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/Contexts.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/Expression.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/ExpressionContext.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/contexts/RunnerContext.kt
library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
library/src/test/kotlin/it/krzeminski/githubactions/dsl/WorkflowBuilderTest.kt
library/src/test/kotlin/it/krzeminski/githubactions/dsl/expressions/ContextsTest.kt
library/src/test/kotlin/it/krzeminski/githubactions/dsl/expressions/PayloadTest.kt
library/src/test/kotlin/it/krzeminski/githubactions/testutils/ShouldMatchFile.kt
library/src/test/kotlin/it/krzeminski/githubactions/yaml/JobsToYamlTest.kt
library/src/test/resources/expected/workflow-expr-typesafe.yml
library/src/test/resources/payloads/runner.json
script-generator/src/test/kotlin/generated/AllTriggers.kt
script-generator/src/test/kotlin/generated/DockerImage.kt
script-generator/src/test/kotlin/generated/GenerateWrappers.kt
script-generator/src/test/kotlin/generated/GeneratedSource.kt
script-generator/src/test/kotlin/generated/NodeJsPackage.kt
script-generator/src/test/kotlin/generated/RefreshversionsBuild.kt
script-generator/src/test/kotlin/generated/RefreshversionsPr.kt
script-generator/src/test/kotlin/generated/RefreshversionsWebsite.kt
script-generator/src/test/kotlin/generated/UpdateGradleWrapper.kt

Splitted from https://github.com/krzema12/github-actions-kotlin-dsl/commit/3341cd22b2c60b01fcf17f0039ea7962d55c8a27
See _The runner context contains information about the runner that is executing the current job_
at https://docs.github.com/en/actions/learn-github-actions/contexts#example-contents-of-the-runner-context

type-safe expressions - runner

---

docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/axelop/GooglejavaformatActionV3.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

[#315] feat(wrappers): add axel-op/googlejavaformat-action@v3

---

library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/Contexts.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/contexts/FunctionsContext.kt
library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
library/src/test/kotlin/it/krzeminski/githubactions/dsl/expressions/ContextsTest.kt
library/src/test/resources/expected/workflow-expr-typesafe.yml

This one should be pretty straight forward
Reference: https://docs.github.com/en/actions/learn-github-actions/expressions#functions

type-safe functions

---

docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/borales/ActionsYarnV3.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

The author published a tag with major version, so it's possible to use
it.

[#333] feat(wrappers): use major version for Borales/actions-yarn@v3

---

wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt

fix #335: suggestVersions should ignore deprecated wrappers

---

.github/workflows/integration_tests_trivial_workflow.yaml
library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt

Ideally there should be more tests, but let's take it step by step.

[#87] test(library): make one integration test run on GitHub

---

.github/workflows/Integration tests - trivial workflow.yaml
library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt

This function will be used by other integration tests. It does make
some assumptions and limits what can be tested, but it's good enough
for now.

[#87] test(library): extract GitHub integration test logic to function

---

docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/w9jds/FirebaseActionV11.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

[#397] feat(actions): add w9jds/firebase-action@11.5.0

---

.github/workflows/Integration tests - type-safe expressions.yaml
library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt

Works as expected now ([link](https://github.com/krzema12/github-actions-kotlin-dsl/runs/7787666068?check_suite_focus=true)):

[#400] test(library): fix integration test for type-safe expressions

---

script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptgenerator/Main.kt

Thank you for the cool project!
This is just a small typo fix I've noticed while trying the script generator

chore: Fix typo in scriptgenerator

---

.github/workflows/Integration tests - step with outputs.yaml
library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt

The removed line was reported as invalid by GitHub:
```
Unrecognized named-value: 'step-0'
```

test(library): fix integration test with outputs

---

docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/sonarsource/SonarcloudGithubActionV1.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt

[#410] feat(actions): add SonarSource/sonarcloud-github-action@v1.6

---

library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/Expression.kt
library/src/test/kotlin/it/krzeminski/githubactions/dsl/expressions/ContextsTest.kt

Resolves #400
Implement simple solution described at
https://github.com/krzema12/github-actions-kotlin-dsl/issues/400#issuecomment-1212297812

[#400] fix(library): correctly serialize env vars in type-safe expressions 

---

docs/index.md
mkdocs.yml

docs: update library name in website title

---

docs/supported-actions.md
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt

[#407] docs: mark actions providing typings

---

docs/user-guide/getting_started.md

update Checkout V2 -> V3 in example

---

renovate.json

It relies on PR checks to be green. Still wait for human approval for major version changes.

chore: automerge Renovate minor and patch version updates

---

wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsTest.kt

[#545] fix(wrapper-generator): don't suggest old major versions

---

wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/ClassNaming.kt
wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/ClassNamingTest.kt
wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsTest.kt

[#556] feat(wrapper-generator): remove support for non-major versions

---

library/build.gradle.kts

[#501] chore(library): configure mutation testing

---

actions/madhead/intellij-http-client-action/v0/commit-hash.txt
docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/madhead/IntellijHttpClientActionV0.kt

feat(actions): add madhead/intellij-http-client-action@v0

---

library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
library/src/main/kotlin/it/krzeminski/githubactions/domain/Step.kt
library/src/main/kotlin/it/krzeminski/githubactions/domain/Workflow.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/HasCustomArguments.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/JobBuilder.kt
library/src/main/kotlin/it/krzeminski/githubactions/dsl/WorkflowBuilder.kt
library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
library/src/main/kotlin/it/krzeminski/githubactions/yaml/ObjectToYaml.kt
library/src/main/kotlin/it/krzeminski/githubactions/yaml/StepsToYaml.kt
library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
library/src/test/kotlin/it/krzeminski/githubactions/yaml/JobsToYamlTest.kt
library/src/test/kotlin/it/krzeminski/githubactions/yaml/ObjectToYamlTest.kt
library/src/test/kotlin/it/krzeminski/githubactions/yaml/StepsToYamlTest.kt

[#627] fix(library): correctly serialize empty and null-y strings

---

CONTRIBUTING.md
actions/burrunan/gradle-cache-action/v1/commit-hash.txt
automation/typings/src/main/kotlin/it/krzeminski/githubactions/actionsmetadata/ActionsMetadataReading.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/metadata/MetadataReading.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/types/TypesProviding.kt
docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/burrunan/GradleCacheActionV1.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/stefanzweifel/GitAutoCommitActionV4.kt

Add burrunan/gradle-cache-action@v1 (#641)

---

actions/actions/cache/v3/restore/action-types.yml
actions/actions/cache/v3/save/action-types.yml
automation/typings/src/main/kotlin/it/krzeminski/githubactions/actionsmetadata/ActionsMetadataReading.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TextTransformation.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/metadata/MetadataReading.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/types/TypesProviding.kt
automation/wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/ClassNamingTest.kt
automation/wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TextTransformationTest.kt
docs/supported-actions.md
library/src/gen/kotlin/it/krzeminski/githubactions/actions/actions/CacheRestoreV3.kt
library/src/gen/kotlin/it/krzeminski/githubactions/actions/actions/CacheSaveV3.kt

Support actions in subdirectories

---

automation/typings/src/main/kotlin/it/krzeminski/githubactions/actionsmetadata/model/ActionCoords.kt
automation/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt

[#648] fix(wrapper-generator): adjust action versions job after adding support for actions in subdirectories

---

docs/requirements.txt
docs/user-guide/compensating-librarys-missing-features.md
docs/user-guide/getting_started.md
docs/user-guide/job-outputs.md
docs/user-guide/type-safe-expressions.md
docs/user-guide/using-actions.md
library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/CompensatingLibrarysMissingFeaturesSnippets.kt
library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/GettingStartedSnippets.kt
library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/JobOutputsSnippets.kt
library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/TypeSafeExpressionsSnippets.kt
library/src/test/kotlin/it/krzeminski/githubactions/docsnippets/UsingActionsSnippets.kt
mkdocs.yml

In 1 - 2 weeks the pymdown extensions version should be finally released.
But here you can already see the changes with the beta version. :-)
If you don't mind using the beta version, you can of course already merge it.
It is just in draft state because of the beta version.

docs: use new pymdown-extensions that is able to unindent snippets

---

library/src/main/kotlin/it/krzeminski/githubactions/domain/triggers/Schedule.kt
library/src/test/kotlin/it/krzeminski/githubactions/domain/triggers/ScheduleTest.kt

[#642] fix(library): support named values in cron expression

---

README.md

fix: doc link

---

script-generator/web/build.gradle.kts
script-generator/web/src/main/kotlin/io/github/typesafegithub/workflows/scriptgenerator/rest/Main.kt
settings.gradle.kts

Part of #571.
Calling:
```
curl 'http://0.0.0.0:8080/api/yaml-to-kotlin' -X POST -H 'Content-Type: application/json' -d "{\"yaml\": \"name: Test\non:\n  push:\"}"
```
Response:
```
{"kotlinScript":"#!/usr/bin/env kotlin\n\n@file:DependsOn(\"io.github.typesafegithub:github-workflows-kt:0.41.0\")\n\nimport io.github.typesafegithub.workflows.domain.Workflow\nimport io.github.typesafegithub.workflows.domain.triggers.Push\nimport io.github.typesafegithub.workflows.dsl.expressions.expr\nimport io.github.typesafegithub.workflows.dsl.workflow\nimport io.github.typesafegithub.workflows.yaml.toYaml\nimport io.github.typesafegithub.workflows.yaml.writeToFile\nimport java.nio.`file`.Paths\n\npublic val workflowTest: Workflow = workflow(\n      name = \"Test\",\n      on = listOf(\n        Push(),\n …
```

WIP: expose rest server

---

buildSrc/src/main/kotlin/buildsrc/convention/dsl-publishing.gradle.kts
jitpack.yml

chore(ci): Fix JitPack building

---

automation/wrapper-generator/src/main/kotlin/io/github/typesafegithub/workflows/wrappergenerator/versions/SuggestVersions.kt

[#782] fix(wrapper-generator): create parent directory for suggestVersions.md

---

README.md
docs/index.md

[#855] docs: fix English in catchphrase

---

automation/code-generator/build.gradle.kts
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/GitHubPullRequestCreation.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/Http.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersions.kt

Before this change, okhttp and ktor client were used. Let's use the first-party solution.

Remove dependency on okhttp

---

docs/feature-coverage.md
library/api/library.api
library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Job.kt
library/src/main/kotlin/io/github/typesafegithub/workflows/dsl/Container.kt
library/src/main/kotlin/io/github/typesafegithub/workflows/dsl/JobBuilder.kt
library/src/main/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilder.kt
library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ContainerToYaml.kt
library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/JobsToYaml.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/domain/ContainerTest.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/yaml/ContainerToYamlTest.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/yaml/JobsToYamlTest.kt

[#883] feat(library): add support for job.container and job.services

---

.github/workflows/_shared.main.kts
.github/workflows/actions-versions.yaml
.github/workflows/build.yaml
.github/workflows/check-if-wrappers-up-to-date.yaml
.github/workflows/create-action-update-prs.yaml
.github/workflows/release-docs.yaml
.github/workflows/release.yaml
README.md

So that caching is handled by gradle/gradle-build-action.
https://kotlinlang.slack.com/archives/C02UUATR7RC/p1687961427696449

fix(ci): disable interfering Gradle caching in setup-java

---

library/api/library.api
library/src/main/kotlin/io/github/typesafegithub/workflows/domain/RunnerType.kt
library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/JobsToYaml.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/domain/RunnerTypeTest.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/yaml/JobsToYamlTest.kt

[#750] feat(library): implement Labelled and Group runner types

---

library/build.gradle.kts
library/src/test/kotlin/io/github/typesafegithub/workflows/NonCompilableTest.kt

[#868] test(library): add tests for non-compilable cases

---

README.md
docs/index.md
library/build.gradle.kts
mkdocs.yml

[#855] docs: adjust intro, title and README badges

---

.github/workflows/Integration tests - job condition.yaml
.github/workflows/Integration tests - step with outputs.yaml
.github/workflows/Integration tests - trivial workflow.yaml
.github/workflows/Integration tests - type-safe expressions.yaml
docs/supported-actions.md
library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/NonCompilableTest.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/docsnippets/GettingStartedSnippets.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/dsl/JobBuilderTest.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/yaml/StepsToYamlTest.kt

There were several problems with CI along the way. This PR brings things to a consistent state.

fix(ci): adjust after incorrect bump of actions/checkout

---

automation/action-binding-generator/api/action-binding-generator.api
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TextTransformation.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt

Similarly like in the previous commit.

[#941] refactor(automation): include package name in binding object

---

automation/action-binding-generator/api/action-binding-generator.api
automation/action-binding-generator/build.gradle.kts
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/InputNullability.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/MetadataReading.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingSuggestions.kt
automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerationTest.kt
automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/InputNullabilityTest.kt
automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingSuggestionsTest.kt
automation/code-generator/build.gradle.kts
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersions.kt
automation/typings/src/main/kotlin/io/github/typesafegithub/workflows/actionsmetadata/model/ActionCoords.kt
settings.gradle.kts

Another step towards making action-binding-generator a deployable library.

[#941] refactor: inline metadata-reading module

---

automation/action-binding-generator/build.gradle.kts
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ClassNaming.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TextUtils.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingGeneration.kt
automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TextUtilsTest.kt
automation/code-generator/build.gradle.kts
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/dsl/expressions/GenerateEventPayloads.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/dsl/expressions/TextUtils.kt
automation/code-generator/src/test/kotlin/io/github/typesafegithub/workflows/dsl/expressions/TextUtilsTest.kt
automation/metadata-reading/build.gradle.kts
automation/text-utils/build.gradle.kts
settings.gradle.kts

Another step towards making action-binding-generator a deployable library.

[#941] refactor: inline text-utils module

---

.github/workflows/_shared.main.kts
.github/workflows/build.main.kts
.github/workflows/build.yaml
.github/workflows/release.main.kts
automation/action-binding-generator/build.gradle.kts
build.gradle.kts
buildSrc/src/main/kotlin/buildsrc/convention/action-binding-generator-publishing.gradle.kts
buildSrc/src/main/kotlin/buildsrc/convention/dsl-publishing.gradle.kts
library/build.gradle.kts

[#774] ci: publish snapshots for main branch

---

automation/action-binding-generator/api/action-binding-generator.api
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/ClassNaming.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/LibraryVersion.kt
automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerationTest.kt
library/build.gradle.kts

[#941] feat(abg): allow generating script-specific code

---

.github/workflows/actions-versions.main.kts
.github/workflows/actions/peter-evans/create-issue-from-file.kt
.github/workflows/generate-action-bindings.main.kts

It's not the ultimate way of how abg will be used, but it's already possible to use it this way experimentally.

[#941] chore: generate first binding using action-binding-generator

---

.github/workflows/Integration tests - custom actions.yaml
library/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt

It's been failing from time to time. Let's try to change some values that can contribute to this.

fix(test): try fixing flaky custom actions integration test

---

.github/workflows/Integration tests - custom actions.yaml
.github/workflows/test-local-action/action.yml
library/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt

Replaces the problematic step with a local action. Let's see if it helps.

[#1077] fix(ci): fix flaky integration test using local action

---

.github/workflows/Integration tests - job outputs mapping.yaml
actions/actions/github-script/v7/action-types.yml
actions/actions/github-script/v7/commit-hash.txt
docs/supported-actions.md
library/src/gen/kotlin/io/github/typesafegithub/workflows/actions/actions/GithubScriptV7.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt

[#1100] feat(actions): add actions/github-script@v7

---

automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProvidingTest.kt

Tested in https://github.com/typesafegithub/github-workflows-kt/actions/runs/6861354515/job/18656913266

fix(automation): fix fetching new types in bindings update job

---

library/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt
library/src/test/kotlin/io/github/typesafegithub/workflows/RunOnGitHubTest.kt

It's a preliminary step before further refactoring.

[#1114] test(library): extract tests run on GitHub to separate file

---

automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/ActionsDocsGeneration.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt

refactor(code-generator): move list of actions in docs generation to separate file

---

automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt

Part of #1072.
The typings hosted in this repo will soon be removed.

feat(abg): stop fetching typings hosted with library

---

automation/action-binding-generator/api/action-binding-generator.api
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingActualSource.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingInferredSource.kt
automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerationTest.kt
automation/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProvidingTest.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/ActionsDocsGeneration.kt

refactor(automation): use actual typing source in docs

---

CONTRIBUTING.md

docs: update contributing manual for adding action

---

gradle.properties
library/build.gradle.kts

chore: enable Gradle configuration cache

---

automation/action-binding-generator/api/action-binding-generator.api
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/MetadataReading.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProviding.kt
automation/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypingActualSource.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt

fix(automation): remove caching of action.yml and action-types.yml

---

action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerateActionBindingsCliHelperTest.kt

test(abg): add smoke test for generateActionBindings

---

automation/code-generator/build.gradle.kts
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt

perf(automation): generate bindings in parallel

---

docs/faq.md

docs: add FAQ item about another stale cache problem

---

action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/TypesProvidingTest.kt

Part of #1073.
I'm going to introduce an important change here, so let's first ensure there's proper test coverage.

test(abg): add tests for order of using typings from various sources

---

action-binding-generator/api/action-binding-generator.api
action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerateActionBindingsCliHelper.kt
action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/Generation.kt
action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/annotations/ExperimentalClientSideBindings.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerateActionBindingsCliHelperTest.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/GenerationTest.kt
github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/annotations/ExperimentalClientSideBindings.kt

feat!: mark client-side bindings as experimental

---

automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersions.kt
automation/code-generator/src/test/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersionsTest.kt

Makes it easier to review what actually changed between the versions.

feat(automation): add links to diffs between major versions

---

automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt

Tested on https://github.com/typesafegithub/github-workflows-kt/pull/1270

fix(automation): create updating PRs against files from repo

---

action-binding-generator/api/action-binding-generator.api
action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt

feat(abg): add versioned JAR mode

---

jit-binding-server/build.gradle.kts

feat(jit-binding-server): configure publishing to DockerHub

---

maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt

fix(jit): use proper mode when generating bindings

---

action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt

To be able to reuse it easily.

test(abg): extract metadata and typings for all types of inputs

---

action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionForGeneratedJar.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt

To ensure the code compiles fine.

test(abg): exercise JAR mode for all typings

---

.github/workflows/end-to-end-tests.main.kts
.github/workflows/end-to-end-tests.yaml
.github/workflows/test-script-consuming-jit-bindings.main.do-not-compile.kts
jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt

test(jit): add end-to-end test

---

.github/workflows/bindings-server.main.kts
.github/workflows/bindings-server.yaml

feat(ci): refactor bindings server pipeline for deployment

---

.github/workflows/bindings-server.main.kts
.github/workflows/bindings-server.yaml

feat(ci): deploy bindings server image to DockerHub

---

.github/workflows/test-script-consuming-jit-bindings.main.do-not-compile.kts
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt

feat(server): support nested actions

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
maven-binding-builder/build.gradle.kts
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PackageArtifactsBuilding.kt

feat(server): serve maven-metadata.xml

---

.github/workflows/bindings-server.main.kts
.github/workflows/bindings-server.yaml
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt

fix(server): correctly generate maven-metadata.xml for nested actions

---

action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/metadata/MetadataReading.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/GenerationTest.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/GenerationEntryPoint.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/updating/CreateActionUpdatePRs.kt
automation/code-generator/src/main/kotlin/io/github/typesafegithub/workflows/codegenerator/versions/SuggestVersions.kt
jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt

fix(server): return HTTP 404 if no action found

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt

feat(server): log each action request

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt

feat(server): cache also non-existence of action

---

docs/feature-coverage.md
github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/Environment.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/Job.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/dsl/JobBuilder.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilder.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/JobsToYaml.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/yaml/JobsToYamlTest.kt

feat(dsl): add environment to job

---

github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt

test(dsl): make integration tests not use toYaml()

---

.github/workflows/end-to-end-tests.main.kts
github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/Workflow.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilder.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ConsistencyCheckJobConfig.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt

chore(dsl)!: restructure API for configuring YAML consistency check job

---

maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/ZipUtils.kt

fix(server): produce deterministic JARs

---

MAINTENANCE.md

0.20.0 looks weird given that the library is already stable.

docs: adjust version in maintenance

---

buildSrc/src/main/kotlin/buildsrc/convention/duplicate-versions.gradle.kts
github-workflows-kt/build.gradle.kts

A step towards automating updating the versions.

chore: extract duplicate version checking to convention plugin

---

.github/workflows/actions-versions.main.kts
.github/workflows/bindings-server.main.kts
.github/workflows/build.main.kts
.github/workflows/check-if-action-bindings-up-to-date.main.kts
.github/workflows/create-action-update-prs.main.kts
.github/workflows/end-to-end-tests.main.kts
.github/workflows/gradle-wrapper-validation.main.kts
.github/workflows/release-common.main.kts
.github/workflows/release-docs.main.kts
.github/workflows/release.main.kts
.github/workflows/setup-java.main.kts
.github/workflows/setup-python.main.kts
docs/user-guide/migrating-to-Maven-based-bindings.md

refactor(ci): use new URL for bindings server

---

action-updates-checker/src/test/kotlin/io/github/typesafegithub/workflows/updates/ReportingTest.kt

refactor: migrate remaining usages of returned Workflow to callback API

---

automation/code-generator/build.gradle.kts

chore(code-generator): remove unused dependencies

---

github-workflows-kt/build.gradle.kts

chore: remove leftover config for bundled bindings

---

maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PomBuilding.kt

Hoping that Renovate will join PRs like https://github.com/typesafegithub/github-workflows-kt/pull/1572 and https://github.com/typesafegithub/github-workflows-kt/pull/1571

fix(server): fix URL to action repo for subactions

---

github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/Job.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/Step.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/StepsToYaml.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/domain/StepTest.kt

feat(library): make outputs accessible for all steps

---

.github/workflows/end-to-end-tests.main.kts
.github/workflows/end-to-end-tests.yaml
github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/actions/Action.kt

feat(library): support getting uses string and YAML arguments as string (#1583)

---

.github/workflows/test-script-consuming-jit-bindings.main.do-not-compile.kts

test: check if untyped action has untyped binding

---

.github/workflows/build.yaml

Caused by a bad manual update.

ci: sync YAML for Build workflow

---

action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputs.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithDeprecatedInputAndNameClash.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithFancyCharsInDocs.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithInputsSharingType.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithNoTypings_Untyped.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithOutputs.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithSomeOptionalInputs.kt
action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/SimpleActionWithRequiredStringInputs.kt

Or Kotlin Poet sometimes breaks before the "to" which is illegal.

fix(abg): Use "a.to(b)" instead of "a to b"

---

maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/Md5Checksum.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PackageArtifactsBuilding.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt

fix(abg): provide checksum for maven metadata

---

shared-internal/src/test/kotlin/io/github/typesafegithub/workflows/shared/internal/model/VersionTest.kt

Part of #1670.
Adding the test before fixing behavior of this method.

test: add tests for Version.isMajorVersion

---

shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/model/Version.kt
shared-internal/src/test/kotlin/io/github/typesafegithub/workflows/shared/internal/model/VersionTest.kt

fix(shared): adjust how major version is inferred

---

docs/projects-using-this-library.md

https://github.com/spockframework/spock/pull/1630 has been merged 🎉

docs: add Spock to projects using the lib

---

github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ConsistencyCheckJob.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt

refactor(library): extract consistency job check creation to separate file

---

github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ConsistencyCheckJob.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ConsistencyCheckJobConfig.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt

Part of #1765.
If enabled, mitigates availability issues with the bindings server in the consistency check job.

feat(library): allow fallback to local bindings server in consistency check job

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/OpenTelemetryConfig.kt

To debug a problem of disappearing spans/metrics from Jaeger and Grafana.

feat(server): add logging around configuring OpenTelemetry

---

github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/triggers/WorkflowCall.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/TriggersToYaml.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/yaml/TriggersToYamlTest.kt

Closes https://github.com/typesafegithub/github-workflows-kt/issues/614.

feat(library): add properties to WorkflowCall trigger

---

action-binding-generator/api/action-binding-generator.api
shared-internal/build.gradle.kts
shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/model/Version.kt
shared-internal/src/test/kotlin/io/github/typesafegithub/workflows/shared/internal/model/GithubApiTest.kt
shared-internal/src/test/kotlin/io/github/typesafegithub/workflows/shared/internal/model/VersionTest.kt

Part of https://github.com/typesafegithub/github-workflows-kt/issues/1855.
Prior to making functional changes to the production code, let's add tests that will help us ensure the issue will get fixed in the next PR(s).

test(shared): add basic tests for fetching available versions

---

.github/workflows/bindings-server.main.kts
.github/workflows/bindings-server.yaml
shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GitHubApp.kt

Reverts typesafegithub/github-workflows-kt#1885
Getting some failures.

Revert "feat(server): allow configuring client ID and installation ID vial env vars"

---

jit-binding-server/build.gradle.kts
jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Plugins.kt

Going with the flow of https://github.com/typesafegithub/github-workflows-kt/pull/1890.

chore(server): add detekt linter

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt

With the loading cache you centrally define the loading strategy, which enables to later just use `get` for example, or `getAll` without having to specify the strategy in each call. 
It is also a requirement for using `refreshAfterWrite`.

chore(server): use loading cache instead of normal cache

---

shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
shared-internal/src/test/kotlin/io/github/typesafegithub/workflows/shared/internal/model/GithubApiTest.kt

Fixes #1904
When using `ktor-client` you have to manage its lifecycle.
That means, if you create a `HttpClientEngine` manually, you have to  also `close()` it if it is no longer needed to free resources.
If you create the `HttpClient` with an `HttpClientEngineFactory` instead, `ktor-client` is responsible to manage its lifecycle.
And if you create an `HttpClient`, you also have to `close()` it if it is no longer needed to free resources, and also that the engine is closed if it is managed by `ktor-client`.
Before this PR engines were created manually but never closed and clients were created but never closed.
This lead to the problem that requests to the GitHub API became slower and slower and eventually fail with GitHub closing or rejecting the connections.
From evidence I guess that the …

fix(server): properly handle the lifecycle of ktor-client

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt

feat(server): cache the generation of the metadata files

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PackageArtifactsBuilding.kt

feat(server): cache version artifacts if metadata is requested

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt

To improve testability, for the purpose of testing the fix in https://github.com/typesafegithub/github-workflows-kt/pull/1924

refactor(server): allow injecting logic for building version artifacts

---

jit-binding-server/build.gradle.kts
jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutesTest.kt

To be able to test the fix in https://github.com/typesafegithub/github-workflows-kt/pull/1924.

test(server): add test showing incorrect behavior for failed binding generation

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutes.kt
jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutesTest.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/PackageArtifactsBuilding.kt

Part of https://github.com/typesafegithub/github-workflows-kt/issues/1938.
To be able to mock it in tests.

refactor(server): allow injecting logic for building package artifacts

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutesTest.kt

Part of https://github.com/typesafegithub/github-workflows-kt/issues/1938.
Adding tests, especially the one capturing the current buggy behavior.

test(server): add tests for metadata routes

---

github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ContextMapping.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/yaml/ContextMappingTest.kt
github-workflows-kt/src/test/resources/contexts/github.json

Part of https://github.com/typesafegithub/github-workflows-kt/issues/1946.

test(library): add tests for reading contexts in Kotlin-based steps

---

github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/contexts/GithubContext.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/yaml/ContextMappingTest.kt
github-workflows-kt/src/test/resources/contexts/github-all-fields.json

Closes https://github.com/typesafegithub/github-workflows-kt/issues/1946

feat(library): allow accessing base_ref in Kotlin-based steps

---

jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutes.kt
jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/ArtifactRoutesTest.kt
jit-binding-server/src/test/kotlin/io/github/typesafegithub/workflows/jitbindingserver/MetadataRoutesTest.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/VersionArtifactsBuilding.kt

Thanks to this, we'll be able to monitor the source of typings, and also proactively add typings for untyped actions.

feat(server): add info about typing's source to metrics

---

github-workflows-kt/api/github-workflows-kt.api
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/dsl/expressions/Contexts.kt
github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/dsl/expressions/contexts/VarsContext.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/docsnippets/TypeSafeExpressionsSnippets.kt
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/dsl/expressions/ContextsTest.kt

feat(library): add the vars context

---

action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProviding.kt

Per https://kotlinlang.slack.com/archives/C02UUATR7RC/p1752619037515229

feat(server): add logging if typings were not found under given URL

---

github-workflows-kt/build.gradle.kts
github-workflows-kt/src/test/kotlin/io/github/typesafegithub/workflows/JavaBytecodeVersionTest.kt
settings.gradle.kts
test-utils/build.gradle.kts
test-utils/src/main/kotlin/io/github/typesafegithub/workflows/testutils/JavaBytecodeUtils.kt
test-utils/src/main/kotlin/io/github/typesafegithub/workflows/testutils/JdkVersionToBytecodeVersion.kt

Part of https://github.com/typesafegithub/github-workflows-kt/issues/1699.

test: refactor and extract util for asserting on bytecode version

---

maven-binding-builder/build.gradle.kts
maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
maven-binding-builder/src/test/kotlin/io/github/typesafegithub/workflows/mavenbinding/JavaBytecodeVersionTest.kt
test-utils/src/main/kotlin/io/github/typesafegithub/workflows/testutils/JavaBytecodeUtils.kt
test-utils/src/main/kotlin/io/github/typesafegithub/workflows/testutils/JdkVersionToBytecodeVersion.kt

Part of https://github.com/typesafegithub/github-workflows-kt/issues/1699.

test: add test for bytecode version of bindings
